"""empty message

Revision ID: 12938c55358d
Revises: 487901ef3002
Create Date: 2020-01-09 13:02:03.637121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12938c55358d'
down_revision = '487901ef3002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('date', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'date')
    # ### end Alembic commands ###
