"""empty message

Revision ID: 1f52db591e69
Revises: 26da937759d4
Create Date: 2020-01-16 17:34:13.914605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f52db591e69'
down_revision = '26da937759d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests')
    op.drop_table('testquestions')
    op.drop_table('questions')
    op.add_column('material_type', sa.Column('custom_template', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_type', 'custom_template')
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.TEXT(), nullable=True),
    sa.Column('type', sa.INTEGER(), nullable=True),
    sa.Column('grade', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testquestions',
    sa.Column('test_id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('test_id', 'question_id')
    )
    op.create_table('tests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('grade', sa.INTEGER(), nullable=True),
    sa.Column('comments', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
