"""empty message

Revision ID: 26da937759d4
Revises: 12938c55358d
Create Date: 2020-01-12 22:53:32.030295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26da937759d4'
down_revision = '12938c55358d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_type', sa.Column('instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_type', 'instructions')
    # ### end Alembic commands ###
