"""empty message

Revision ID: c4af5af81c77
Revises: 195d0ca34798
Create Date: 2020-03-06 11:03:08.587549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4af5af81c77'
down_revision = '195d0ca34798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_material', sa.Column('bonus_available', sa.Integer(), nullable=True))
    op.add_column('lesson_material', sa.Column('scoring_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_material', 'bonus_available')
    op.drop_column('lesson_material', 'scoring_comment')
    # ### end Alembic commands ###
